import React, { useState, useEffect } from 'react';
import { supabase } from '../config';
import { TrendingUp, Users, Eye, Calendar, Download, BarChart3, Crown } from 'lucide-react';
import { canPerformAction } from '../planLimits';

// PDF Export function (only for Professional plan)
const exportPDF = (stats, orgData) => {
  // Dynamic import to avoid bundle size increase
  import('jspdf').then((jsPDFModule) => {
    const jsPDF = jsPDFModule.default;
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(255, 107, 43); // Orange
    doc.text('DateUp Analytics Report', 105, 20, { align: 'center' });
    
    // Organization info
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Organization: ${orgData.name}`, 20, 35);
    doc.text(`Report Generated: ${new Date().toLocaleDateString()}`, 20, 42);
    
    // Divider line
    doc.setDrawColor(255, 107, 43);
    doc.setLineWidth(0.5);
    doc.line(20, 48, 190, 48);
    
    // Key Metrics
    doc.setFontSize(16);
    doc.setTextColor(10, 22, 40); // Navy
    doc.text('Key Metrics', 20, 58);
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Total Notices: ${stats.totalNotices}`, 20, 68);
    doc.text(`Total Views: ${stats.totalViews}`, 20, 76);
    doc.text(`Average Views per Notice: ${stats.avgViews}`, 20, 84);
    
    // Performance by Tag
    doc.setFontSize(16);
    doc.setTextColor(10, 22, 40);
    doc.text('Performance by Tag', 20, 100);
    
    let yPos = 110;
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    Object.entries(stats.viewsByTag || {}).forEach(([tag, views]) => {
      const percentage = ((views / stats.totalViews) * 100).toFixed(1);
      doc.text(`${tag.charAt(0).toUpperCase() + tag.slice(1)}: ${views} views (${percentage}%)`, 20, yPos);
      yPos += 8;
    });
    
    // Top Notices
    doc.setFontSize(16);
    doc.setTextColor(10, 22, 40);
    doc.text('Top 5 Performing Notices', 20, yPos + 10);
    
    yPos += 20;
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    stats.topNotices?.slice(0, 5).forEach((notice, idx) => {
      doc.text(`${idx + 1}. ${notice.title}`, 20, yPos);
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      doc.text(`   ${notice.views || 0} views • ${new Date(notice.created_at).toLocaleDateString()}`, 20, yPos + 5);
      doc.setFontSize(11);
      doc.setTextColor(0, 0, 0);
      yPos += 12;
    });
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by DateUp Analytics', 105, 285, { align: 'center' });
    
    // Save PDF
    doc.save(`dateup-analytics-${new Date().toISOString().split('T')[0]}.pdf`);
  }).catch(err => {
    console.error('PDF export failed:', err);
    alert('Failed to export PDF. Please try again.');
  });
};

export default function AdvancedAnalytics({ session, orgData }) {
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(true);
  const hasAccess = canPerformAction(orgData, 'advanced_analytics');

  useEffect(() => {
    if (hasAccess) fetchAnalytics();
    else setLoading(false);
  }, [hasAccess]);

  const fetchAnalytics = async () => {
    const { data: notices } = await supabase
      .from('notices')
      .select('*')
      .eq('org_id', session.user.id);

    if (notices) {
      const totalViews = notices.reduce((sum, n) => sum + (n.views || 0), 0);
      const avgViews = notices.length > 0 ? (totalViews / notices.length).toFixed(1) : 0;
      
      // Views by tag
      const viewsByTag = {};
      notices.forEach(n => {
        viewsByTag[n.tag] = (viewsByTag[n.tag] || 0) + (n.views || 0);
      });

      // Top notices
      const topNotices = [...notices]
        .sort((a, b) => (b.views || 0) - (a.views || 0))
        .slice(0, 5);

      setStats({
        totalNotices: notices.length,
        totalViews,
        avgViews,
        viewsByTag,
        topNotices
      });
    }
    setLoading(false);
  };

  if (!hasAccess) {
    return (
      <div style={{ textAlign: 'center', padding: '80px 20px' }}>
        <div style={{
          width: 80,
          height: 80,
          background: 'linear-gradient(135deg, var(--orange), var(--orange-dark))',
          borderRadius: 20,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          margin: '0 auto 24px',
          boxShadow: 'var(--shadow-orange)'
        }}>
          <Crown size={40} color="white" />
        </div>
        <h2 className="text-head" style={{ fontSize: 28, marginBottom: 12 }}>
          Advanced Analytics
        </h2>
        <p className="text-muted" style={{ fontSize: 16, marginBottom: 32, maxWidth: 500, margin: '0 auto 32px' }}>
          Unlock detailed engagement metrics, performance tracking, and exportable reports.
        </p>
        <button
          onClick={() => window.location.href = '/pricing'}
          className="btn btn-primary"
          style={{ fontSize: 16, padding: '14px 32px' }}
        >
          <Crown size={18} />
          Upgrade to Starter - $9.99/mo
        </button>
      </div>
    );
  }

  if (loading) {
    return (
      <div style={{ textAlign: 'center', padding: '60px 0' }}>
        <div className="spinner" style={{ margin: '0 auto' }} />
      </div>
    );
  }

  return (
    <div style={{ maxWidth: 1000, margin: '0 auto' }}>
      <div className="flex-between" style={{ marginBottom: 32 }}>
        <div>
          <h2 className="text-head text-2xl">Advanced Analytics</h2>
          <p className="text-muted" style={{ marginTop: 4 }}>
            Deep insights into your notice performance
          </p>
        </div>
        {orgData?.subscription_plan === 'professional' && (
          <button 
            className="btn btn-secondary"
            onClick={() => exportPDF(stats, orgData)}
          >
            <Download size={16} />
            Export Report
          </button>
        )}
      </div>

      {/* Key Metrics */}
      <div className="stats-grid" style={{ marginBottom: 32 }}>
        <div className="stat-card">
          <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12 }}>
            <BarChart3 size={24} color="var(--orange)" />
            <span className="text-sm text-muted">Total Notices</span>
          </div>
          <div className="stat-num">{stats?.totalNotices || 0}</div>
        </div>
        <div className="stat-card">
          <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12 }}>
            <Eye size={24} color="var(--orange)" />
            <span className="text-sm text-muted">Total Views</span>
          </div>
          <div className="stat-num">{stats?.totalViews || 0}</div>
        </div>
        <div className="stat-card">
          <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12 }}>
            <TrendingUp size={24} color="var(--orange)" />
            <span className="text-sm text-muted">Avg Views/Notice</span>
          </div>
          <div className="stat-num">{stats?.avgViews || 0}</div>
        </div>
      </div>

      {/* Views by Tag */}
      <div className="card" style={{ marginBottom: 32 }}>
        <h3 className="text-head" style={{ fontSize: 18, marginBottom: 20 }}>
          Performance by Tag
        </h3>
        {Object.entries(stats?.viewsByTag || {}).map(([tag, views]) => (
          <div key={tag} style={{ marginBottom: 16 }}>
            <div className="flex-between" style={{ marginBottom: 8 }}>
              <span style={{ textTransform: 'capitalize' }}>{tag}</span>
              <span className="text-orange" style={{ fontWeight: 600 }}>{views} views</span>
            </div>
            <div className="quota-bar-bg">
              <div
                className="quota-bar-fill"
                style={{ width: `${(views / (stats?.totalViews || 1)) * 100}%` }}
              />
            </div>
          </div>
        ))}
      </div>

      {/* Top Notices */}
      <div className="card">
        <h3 className="text-head" style={{ fontSize: 18, marginBottom: 20 }}>
          Top 5 Notices
        </h3>
        {stats?.topNotices?.map((notice, idx) => (
          <div
            key={notice.id}
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: '12px 0',
              borderBottom: idx < 4 ? '1px solid rgba(255,255,255,0.05)' : 'none'
            }}
          >
            <div style={{ flex: 1 }}>
              <div style={{ fontWeight: 600, marginBottom: 4 }}>{notice.title}</div>
              <div className="text-xs text-muted">
                {new Date(notice.created_at).toLocaleDateString()}
              </div>
            </div>
            <div style={{
              background: 'rgba(255,107,43,0.12)',
              border: '1px solid rgba(255,107,43,0.25)',
              borderRadius: 8,
              padding: '6px 12px',
              color: 'var(--orange)',
              fontWeight: 600,
              fontSize: 14
            }}>
              {notice.views || 0} views
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}